apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: ad9db62c-dc44-4db4-b5c2-bc2da57711d9
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 56dd727b-8e66-4348-9e63-718d1fc1e4c8
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 2b4b160d-3fff-4f83-9328-de4224f6feae
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: relationship-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 6be8b849-0a2a-4310-ab8b-dc39f80b9be8
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: change-intelligence-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: fb7c8b64-2711-44d9-832d-3c8b8f229f7d
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operations-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 8df6207a-8a2e-414b-aed5-617ee15316db
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 7055478a-b394-43c4-91ee-b76122459ebb
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-worker
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: 87c5587e-90c4-444e-9ab2-b11e623c6342
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: outbox-relay
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: f6f97e65-1394-4116-9fd2-f32385862279
automountServiceAccountToken: true
